global:
  scrape_interval: 15s

rule_files:
  - '/etc/prometheus/*.rules'

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: cluster
    file_sd_configs:
      - files: ['/etc/prometheus/cluster.json']

  - job_name: workstations
    file_sd_configs:
      - files: ['/etc/prometheus/workstations.json']
