---
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: nvidia-driver-volume-set
  namespace: kube-system
  labels:
    k8s-app: nvidia-driver-volume
spec:
  selector:
    matchLabels:
      k8s-app: nvidia-driver-volume
  template:
    metadata:
      name: nvidia-driver-volume-deployer
      labels:
        k8s-app: nvidia-driver-volume
        version: '4'
    spec:
      containers:
        - image: bnavetta/nvidia-drivers-deployer
          imagePullPolicy: Always
          name: nvidia-driver-volume-deployer
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /flexmnt
              name: flexvolume-mount
          command:
          - /usr/local/bin/deploy.sh
          - /flexmnt
      volumes:
        - name: flexvolume-mount
          hostPath:
            path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
