---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  restartPolicy: OnFailure
  containers:
    - name: gpu-container
      command:
        - /usr/local/nvidia/bin/nvidia-smi
      image: nvidia/cuda:8.0
      resources:
        limits:
          alpha.kubernetes.io/nvidia-gpu: 1
      volumeMounts:
        - mountPath: /usr/local/nvidia
          name: nvidia-drivers
  volumes:
    - name: nvidia-drivers
      hostPath:
          path: /var/lib/kubernetes-nvidia-drivers/drivers
